name = "FastGroupBy"
uuid = "e6aeac8e-85c6-520e-8612-effc59bc0f33"
authors = ["Dai ZJ <zhuojia.dai@gmail.com>"]
version = "0.2.1"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IndexedTables = "6deec6e2-d858-57c5-ab9b-e6ca5bd20e43"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
SortingAlgorithms = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
SortingLab = "562c1548-17b8-5b69-83cf-d8aebec229f5"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Revise", "BenchmarkTools", "Random"]
